### ISSUE TITLE
[R2V2 dataset download] Permission denied - Maybe you need to change permission over 'Anyone with the link'?

### ISSUE THREAD

**Issue by chi0tzp** [danielgordon10/vince#1]
Hi, 

it seems that there's an issue (possibly related to an gdown's [issue](https://github.com/wkentaro/gdown/issues/43)), which raises the following error during downloading R2V2 dataset files from Google Drive. For instance,

> Permission denied: https://drive.google.com/uc?id=16FCN7dZ4dBUPYSbuaJq4dD3x_SNYRXn1
> Maybe you need to change permission over 'Anyone with the link'?
> 

This happens for the majority of the links found in `r2v2_drive_urls.txt`, all but 6 files, at least in my case.

Also, would that be possible to provide a list of **md5sums** for any file that needs to be downloaded from Google Drive? That would help a lot towards verifying validity of the downloaded files before extracting.

**Comment by danielgordon10** [comment]
I believe gdown gets rate-limited after 20 links for 24 hours. You should still be able to download the links by hand. This kind of sucks, but I didn't want people to have to download one really large file in case it got interrupted. I can make the one-large-file option available, but I'm not sure if it will be more useful.

https://github.com/wkentaro/gdown/issues/43

**Comment by danielgordon10** [comment]
Here is the full dataset as one large tar file. https://drive.google.com/open?id=1JGwb6ai1NugeW7KJDDE7G_bZ54D69teF

**Comment by chi0tzp** [comment]
@danielgordon10 thank you! This actually helps a lot :)

**Comment by whulixiya** [comment]
I met the same error when I try to download many big files from my google drive, have anyone fixed it?
