### ISSUE TITLE
R2V2 version - Paper & public

### ISSUE THREAD

**Issue by ManiadisG** [danielgordon10/vince#2]
Hello,

you mention in the readme that the publicly available version of R2V2 larger than the one used in the paper. I'm assuming that the pretrained weights available for download are also trained on the smaller version.

Is it possible to make the version of R2V2 used to train the models in the paper publicly available?

Alternatively, if the larger version is a superset of the smaller one and includes all of its videos, it would also work to upload the names of the videos in question so that they could be picked from the larger dataset.

**Comment by danielgordon10** [comment]
- The pretrained weights uploaded are trained on the larger R2V2. The larger one was perhaps 25% larger than the original.
- The smaller R2V2 was deleted with no way of restoration. When I first made it, I only saved the video ID, not the frame ID. For release purposes I thought frame ID and video ID would be better. 
- The Resnet 50 results are trained on the larger R2V2. I can't remember about the Resnet 18, but the results should be very similar regardless of the dataset.
