### ISSUE TITLE
Can not reproduce benchmark results

### ISSUE THREAD

**Issue by Endeavour10020** [danielgordon10/vince#3]
Hi, I want to reproduce the benchmark results as the same setting in end_tasks/train_kinetics_400.sh on kinetics 400 dataset, The code I changed in two parts: 
(i): Change kinetics_400_dataset.py which fit my dataset that contains 240618 in train and 19760 in val.
(ii): Change 'self.feature_extractor.restore()' to restore pretrain model. 
The result is shown in val folder in tensorboard. the val accuracy is almost 0.285, leave a large margin of 0.362. Do you use the same setting in val and inference procedure？Do you use apex in training the K400 end task? 
Looking forward to your reply！
![Snipaste_2020-10-17_14-12-26](https://user-images.githubusercontent.com/55418760/96329828-070d3b80-1083-11eb-9343-7e9f5b7ecc13.png)
![Snipaste_2020-10-17_14-13-22](https://user-images.githubusercontent.com/55418760/96329829-08d6ff00-1083-11eb-8fac-94665becff36.png)
![Snipaste_2020-10-17_14-13-31](https://user-images.githubusercontent.com/55418760/96329830-0a082c00-1083-11eb-9094-edc032452ed5.png)

**Comment by Endeavour10020** [comment]
OK, I solved the problems of end task training and achieved the same result as the benchmark provided.

**Comment by danielgordon10** [comment]
@Endeavour10020 What was the issue you fixed?
