### ISSUE TITLE
Reproducing Sup-IN baseline

### ISSUE THREAD

**Issue by xvjiarui** [danielgordon10/vince#4]
Hi @danielgordon10 
I am reproducing the baseline Sup-IN of ResNet 18 on OTB tracking. But directly use pretrained weight from torchvision will get NaN very soon. May I know how you set hyperparameters for imagenet supervised baseline?

**Comment by danielgordon10** [comment]
The hyperparameters I used are the ones in the repo. It could be you're trying to finetune the whole network, but we only train the last layer.
