### ISSUE TITLE
checkpoint path logic issue

### ISSUE THREAD

**Issue by noelcodella** [danielgordon10/vince#6]
Hi,

What's the purpose of line 275 in solvers/vince_solver.py? The args.checkpoint_dir variable is already assigned in arg_parser.py. This is preventing the code from properly loading previous checkpoints specified at the command line. 

Similar issues exist for end_task_base_solver.py (line 116).

Also, how to apply a VINCE trained model to ImageNet task? The instructions are missing. With these issues regarding the checkpoint_dir, it seems impossible?

Thank you.

**Comment by noelcodella** [comment]
Just a note: I noticed the end task will look for a pre-trained model in the checkpoint directory. By fixing the earlier checkpoint path problem, I was able to get the code to successfully load a VINCE pre-trained ResNet18 model and finish an evaluation on ImageNet. But I got a Top-1 number for ImageNet around 43%, which seems higher than the number reported in the paper (40%).

**Comment by danielgordon10** [comment]
The purpose of https://github.com/danielgordon10/vince/blob/master/solvers/vince_solver.py#L275
